trigger:
  batch: true
  branches:
    include:
    - "*"
pr:
  branches:
    include:
    - Master
    - releases/*

variables:
  - name: SolutionBaseName
    value: FH.ServiceDirectory.Admin.Ui
  - name: BuildConfiguration
    value: Release
  - name: BuildPlatform
    value: any cpu
  - group: RELEASE Management Resources
  - group: RELEASE FH.ServiceDirectory.Admin.Ui
  - name: Deploy
    value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))]

resources:
  repositories:
  - repository: self
    type: github

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildConfiguration: $(BuildConfiguration)

- stage: Deploy_Development
  dependsOn: Build
  displayName: Deploy to Development
  condition: and(succeeded(), eq(variables.Deploy, 'true'))
  variables:
  - group: DevTest Management Resources
  - group: Development Shared Resources
  - group: Development FH.ServiceDirectory.Admin.Ui  
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: Development
      ServiceConnection: FH-Development-ARM

- stage: Deploy_Test
  dependson: Build
  displayName: Deploy to Test
  variables:
  - group: DevTest Management Resources
  - group: Test Shared Resources
  - group: Test FH.ServiceDirectory.Admin.Ui
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: Test
      ServiceConnection: FH-Test-ARM

- stage: Deploy_Production
  dependson: Build
  displayName: Deploy to Production
  variables:
  - group: Production Management Resources
  - group: Production Shared Resources
  - group: Production FH.ServiceDirectory.Admin.Ui
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: Test
      ServiceConnection: FH-Test-ARM
