trigger:
  branches:
    include:
    - "*"
pr:
  branches:
    include:
    - Master
    - releases/*
resources:
  repositories:
  - repository: self
    type: git
stages:
- stage: Build
  jobs:
  - job: CodeBuild
    displayName: CodeBuild
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      clean: true
      fetchTags: false
    - task: DotNetCoreCLI@2
      displayName: dotnet restore
      inputs:
        command: restore
        projects: '**/*.csproj'
        noCache: true
    - task: FileTransform@1
      displayName: File Transform
      inputs:
        folderPath: $(System.DefaultWorkingDirectory)
        fileType: json
        targetFiles: src/FamilyHubs.ServiceDirectoryAdminUi.Ui/appsettings.json
    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        projects: '**/*.csproj'
        arguments: '--configuration Release --no-restore'
    - task: DotNetCoreCLI@2
      displayName: dotnet test
      inputs:
        command: test
        projects: '**/*.csproj'
        publishTestResults: true
        arguments: '--configuration Release --no-build /p:CollectCoverage=true /p:CoverletOutput=$(Agent.TempDirectory)/CoverageResults/ /p:MergeWith=$(Agent.TempDirectory)/CoverageResults/coverage.json /p:CoverletOutputFormat="opencover%2cjson"'
    - task: DotNetCoreCLI@2
      displayName: dotnet publish
      inputs:
        command: publish
        publishWebProjects: false #set to false as this setting (which defaults to true) will parse the entire repo for web projects
        projects: |
          **/*.@(Api|Ui).csproj
        arguments: -o $(build.artifactstagingdirectory)/publish -c release --no-build
    - task: CopyFiles@2
      displayName: Copy Files
      inputs:
        Contents: |
          azure/**
        TargetFolder: $(build.artifactstagingdirectory)/publish
        OverWrite: true
    - task: PublishPipelineArtifact@1
      displayName: Publish Pipeline Artifact
      inputs:
        targetPath: $(build.artifactstagingdirectory)/publish
        artifactName: s181-as-fh-sd-admin-ui
  